// ============================================================================
// Seed Data: Reference Tables
// ============================================================================
// ref_countries, ref_languages, ref_currencies, ref_timezones
// All data verified against ISO standards and real-world facts
// ============================================================================

// Explicit seed interfaces — Drizzle's $inferInsert strips nullable columns
// from strict type checking, so we define our own interfaces for seed data.

interface CountrySeed {
  code: string;
  alpha3: string;
  numericCode: string;
  nameEn: string;
  nameHu: string;
  nameDe?: string | null;
  nameNative?: string | null;
  continent: string;
  subRegion?: string | null;
  phoneCode: string;
  defaultCurrency: string;
  primaryLanguage: string;
  flagEmoji?: string | null;
  isEu: boolean;
  isEurozone: boolean;
  isSchengen: boolean;
  marketPriority?: number | null;
  pppMultiplier?: string | null;
  isActive: boolean;
  sortOrder: number;
}

interface LanguageSeed {
  code: string;
  nameEn: string;
  nameHu: string;
  nameNative: string;
  direction: string;
  isAppSupported: boolean;
  isContentLanguage: boolean;
  sortOrder: number;
  isActive: boolean;
}

interface CurrencySeed {
  code: string;
  numericCode?: string | null;
  nameEn: string;
  nameHu: string;
  symbol: string;
  decimalDigits: number;
  thousandsSeparator: string;
  decimalSeparator: string;
  symbolPosition: string;
  formatExample?: string | null;
  isStripeSupported: boolean;
  isActive: boolean;
  sortOrder: number;
}

interface TimezoneSeed {
  tzId: string;
  displayName: string;
  utcOffsetMinutes: number;
  utcOffsetText: string;
  hasDst: boolean;
  countryCode: string;
  sortOrder: number;
  isActive: boolean;
}

// ============================================================================
// 1. COUNTRIES — ISO 3166-1
// ============================================================================

export const countriesData: CountrySeed[] = [
  // ── Target Markets (market_priority = 1) ──────────────────────────────
  {
    code: 'HU',
    alpha3: 'HUN',
    numericCode: '348',
    nameEn: 'Hungary',
    nameHu: 'Magyarország',
    nameDe: 'Ungarn',
    nameNative: 'Magyarország',
    continent: 'Europe',
    subRegion: 'Central Europe',
    phoneCode: '+36',
    defaultCurrency: 'HUF',
    primaryLanguage: 'hu',
    flagEmoji: '🇭🇺',
    isEu: true,
    isEurozone: false,
    isSchengen: true,
    marketPriority: 1,
    pppMultiplier: '0.65',
    isActive: true,
    sortOrder: 1,
  },
  {
    code: 'SK',
    alpha3: 'SVK',
    numericCode: '703',
    nameEn: 'Slovakia',
    nameHu: 'Szlovákia',
    nameDe: 'Slowakei',
    nameNative: 'Slovensko',
    continent: 'Europe',
    subRegion: 'Central Europe',
    phoneCode: '+421',
    defaultCurrency: 'EUR',
    primaryLanguage: 'sk',
    flagEmoji: '🇸🇰',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    marketPriority: 1,
    pppMultiplier: '0.70',
    isActive: true,
    sortOrder: 2,
  },
  {
    code: 'CZ',
    alpha3: 'CZE',
    numericCode: '203',
    nameEn: 'Czechia',
    nameHu: 'Csehország',
    nameDe: 'Tschechien',
    nameNative: 'Česko',
    continent: 'Europe',
    subRegion: 'Central Europe',
    phoneCode: '+420',
    defaultCurrency: 'CZK',
    primaryLanguage: 'cs',
    flagEmoji: '🇨🇿',
    isEu: true,
    isEurozone: false,
    isSchengen: true,
    marketPriority: 1,
    pppMultiplier: '0.70',
    isActive: true,
    sortOrder: 3,
  },
  {
    code: 'HR',
    alpha3: 'HRV',
    numericCode: '191',
    nameEn: 'Croatia',
    nameHu: 'Horvátország',
    nameDe: 'Kroatien',
    nameNative: 'Hrvatska',
    continent: 'Europe',
    subRegion: 'Southern Europe',
    phoneCode: '+385',
    defaultCurrency: 'EUR',
    primaryLanguage: 'hr',
    flagEmoji: '🇭🇷',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    marketPriority: 1,
    pppMultiplier: '0.70',
    isActive: true,
    sortOrder: 4,
  },
  {
    code: 'SI',
    alpha3: 'SVN',
    numericCode: '705',
    nameEn: 'Slovenia',
    nameHu: 'Szlovénia',
    nameDe: 'Slowenien',
    nameNative: 'Slovenija',
    continent: 'Europe',
    subRegion: 'Central Europe',
    phoneCode: '+386',
    defaultCurrency: 'EUR',
    primaryLanguage: 'sl',
    flagEmoji: '🇸🇮',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    marketPriority: 1,
    pppMultiplier: '0.70',
    isActive: true,
    sortOrder: 5,
  },
  {
    code: 'RO',
    alpha3: 'ROU',
    numericCode: '642',
    nameEn: 'Romania',
    nameHu: 'Románia',
    nameDe: 'Rumänien',
    nameNative: 'România',
    continent: 'Europe',
    subRegion: 'Eastern Europe',
    phoneCode: '+40',
    defaultCurrency: 'RON',
    primaryLanguage: 'ro',
    flagEmoji: '🇷🇴',
    isEu: true,
    isEurozone: false,
    isSchengen: true, // Joined Schengen air/sea 2024
    marketPriority: 1,
    pppMultiplier: '0.60',
    isActive: true,
    sortOrder: 6,
  },
  {
    code: 'DE',
    alpha3: 'DEU',
    numericCode: '276',
    nameEn: 'Germany',
    nameHu: 'Németország',
    nameDe: 'Deutschland',
    nameNative: 'Deutschland',
    continent: 'Europe',
    subRegion: 'Western Europe',
    phoneCode: '+49',
    defaultCurrency: 'EUR',
    primaryLanguage: 'de',
    flagEmoji: '🇩🇪',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    marketPriority: 1,
    pppMultiplier: '1.00',
    isActive: true,
    sortOrder: 7,
  },
  {
    code: 'AT',
    alpha3: 'AUT',
    numericCode: '040',
    nameEn: 'Austria',
    nameHu: 'Ausztria',
    nameDe: 'Österreich',
    nameNative: 'Österreich',
    continent: 'Europe',
    subRegion: 'Western Europe',
    phoneCode: '+43',
    defaultCurrency: 'EUR',
    primaryLanguage: 'de',
    flagEmoji: '🇦🇹',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    marketPriority: 1,
    pppMultiplier: '1.00',
    isActive: true,
    sortOrder: 8,
  },

  // ── Secondary Markets (market_priority = 2) ───────────────────────────
  {
    code: 'PL',
    alpha3: 'POL',
    numericCode: '616',
    nameEn: 'Poland',
    nameHu: 'Lengyelország',
    nameDe: 'Polen',
    nameNative: 'Polska',
    continent: 'Europe',
    subRegion: 'Central Europe',
    phoneCode: '+48',
    defaultCurrency: 'PLN',
    primaryLanguage: 'pl',
    flagEmoji: '🇵🇱',
    isEu: true,
    isEurozone: false,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 9,
  },
  {
    code: 'IT',
    alpha3: 'ITA',
    numericCode: '380',
    nameEn: 'Italy',
    nameHu: 'Olaszország',
    nameDe: 'Italien',
    nameNative: 'Italia',
    continent: 'Europe',
    subRegion: 'Southern Europe',
    phoneCode: '+39',
    defaultCurrency: 'EUR',
    primaryLanguage: 'it',
    flagEmoji: '🇮🇹',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 10,
  },
  {
    code: 'FR',
    alpha3: 'FRA',
    numericCode: '250',
    nameEn: 'France',
    nameHu: 'Franciaország',
    nameDe: 'Frankreich',
    nameNative: 'France',
    continent: 'Europe',
    subRegion: 'Western Europe',
    phoneCode: '+33',
    defaultCurrency: 'EUR',
    primaryLanguage: 'fr',
    flagEmoji: '🇫🇷',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 11,
  },
  {
    code: 'ES',
    alpha3: 'ESP',
    numericCode: '724',
    nameEn: 'Spain',
    nameHu: 'Spanyolország',
    nameDe: 'Spanien',
    nameNative: 'España',
    continent: 'Europe',
    subRegion: 'Southern Europe',
    phoneCode: '+34',
    defaultCurrency: 'EUR',
    primaryLanguage: 'es',
    flagEmoji: '🇪🇸',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 12,
  },
  {
    code: 'PT',
    alpha3: 'PRT',
    numericCode: '620',
    nameEn: 'Portugal',
    nameHu: 'Portugália',
    nameDe: 'Portugal',
    nameNative: 'Portugal',
    continent: 'Europe',
    subRegion: 'Southern Europe',
    phoneCode: '+351',
    defaultCurrency: 'EUR',
    primaryLanguage: 'pt',
    flagEmoji: '🇵🇹',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 13,
  },
  {
    code: 'CH',
    alpha3: 'CHE',
    numericCode: '756',
    nameEn: 'Switzerland',
    nameHu: 'Svájc',
    nameDe: 'Schweiz',
    nameNative: 'Schweiz',
    continent: 'Europe',
    subRegion: 'Western Europe',
    phoneCode: '+41',
    defaultCurrency: 'CHF',
    primaryLanguage: 'de',
    flagEmoji: '🇨🇭',
    isEu: false,
    isEurozone: false,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 14,
  },
  {
    code: 'GB',
    alpha3: 'GBR',
    numericCode: '826',
    nameEn: 'United Kingdom',
    nameHu: 'Egyesült Királyság',
    nameDe: 'Vereinigtes Königreich',
    nameNative: 'United Kingdom',
    continent: 'Europe',
    subRegion: 'Northern Europe',
    phoneCode: '+44',
    defaultCurrency: 'GBP',
    primaryLanguage: 'en',
    flagEmoji: '🇬🇧',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    marketPriority: 2,
    isActive: true,
    sortOrder: 15,
  },
  {
    code: 'NL',
    alpha3: 'NLD',
    numericCode: '528',
    nameEn: 'Netherlands',
    nameHu: 'Hollandia',
    nameDe: 'Niederlande',
    nameNative: 'Nederland',
    continent: 'Europe',
    subRegion: 'Western Europe',
    phoneCode: '+31',
    defaultCurrency: 'EUR',
    primaryLanguage: 'nl',
    flagEmoji: '🇳🇱',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 16,
  },
  {
    code: 'BE',
    alpha3: 'BEL',
    numericCode: '056',
    nameEn: 'Belgium',
    nameHu: 'Belgium',
    nameDe: 'Belgien',
    nameNative: 'België',
    continent: 'Europe',
    subRegion: 'Western Europe',
    phoneCode: '+32',
    defaultCurrency: 'EUR',
    primaryLanguage: 'nl',
    flagEmoji: '🇧🇪',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 17,
  },
  {
    code: 'SE',
    alpha3: 'SWE',
    numericCode: '752',
    nameEn: 'Sweden',
    nameHu: 'Svédország',
    nameDe: 'Schweden',
    nameNative: 'Sverige',
    continent: 'Europe',
    subRegion: 'Northern Europe',
    phoneCode: '+46',
    defaultCurrency: 'SEK',
    primaryLanguage: 'sv',
    flagEmoji: '🇸🇪',
    isEu: true,
    isEurozone: false,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 18,
  },
  {
    code: 'NO',
    alpha3: 'NOR',
    numericCode: '578',
    nameEn: 'Norway',
    nameHu: 'Norvégia',
    nameDe: 'Norwegen',
    nameNative: 'Norge',
    continent: 'Europe',
    subRegion: 'Northern Europe',
    phoneCode: '+47',
    defaultCurrency: 'NOK',
    primaryLanguage: 'no',
    flagEmoji: '🇳🇴',
    isEu: false,
    isEurozone: false,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 19,
  },
  {
    code: 'DK',
    alpha3: 'DNK',
    numericCode: '208',
    nameEn: 'Denmark',
    nameHu: 'Dánia',
    nameDe: 'Dänemark',
    nameNative: 'Danmark',
    continent: 'Europe',
    subRegion: 'Northern Europe',
    phoneCode: '+45',
    defaultCurrency: 'DKK',
    primaryLanguage: 'da',
    flagEmoji: '🇩🇰',
    isEu: true,
    isEurozone: false,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 20,
  },
  {
    code: 'FI',
    alpha3: 'FIN',
    numericCode: '246',
    nameEn: 'Finland',
    nameHu: 'Finnország',
    nameDe: 'Finnland',
    nameNative: 'Suomi',
    continent: 'Europe',
    subRegion: 'Northern Europe',
    phoneCode: '+358',
    defaultCurrency: 'EUR',
    primaryLanguage: 'fi',
    flagEmoji: '🇫🇮',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 21,
  },
  {
    code: 'IE',
    alpha3: 'IRL',
    numericCode: '372',
    nameEn: 'Ireland',
    nameHu: 'Írország',
    nameDe: 'Irland',
    nameNative: 'Éire',
    continent: 'Europe',
    subRegion: 'Northern Europe',
    phoneCode: '+353',
    defaultCurrency: 'EUR',
    primaryLanguage: 'en',
    flagEmoji: '🇮🇪',
    isEu: true,
    isEurozone: true,
    isSchengen: false,
    marketPriority: 2,
    isActive: true,
    sortOrder: 22,
  },
  {
    code: 'IS',
    alpha3: 'ISL',
    numericCode: '352',
    nameEn: 'Iceland',
    nameHu: 'Izland',
    nameDe: 'Island',
    nameNative: 'Ísland',
    continent: 'Europe',
    subRegion: 'Northern Europe',
    phoneCode: '+354',
    defaultCurrency: 'ISK',
    primaryLanguage: 'is',
    flagEmoji: '🇮🇸',
    isEu: false,
    isEurozone: false,
    isSchengen: true,
    marketPriority: 2,
    isActive: true,
    sortOrder: 23,
  },

  // ── Other European (sort 24+) ─────────────────────────────────────────
  {
    code: 'BG',
    alpha3: 'BGR',
    numericCode: '100',
    nameEn: 'Bulgaria',
    nameHu: 'Bulgária',
    nameDe: 'Bulgarien',
    nameNative: 'България',
    continent: 'Europe',
    subRegion: 'Eastern Europe',
    phoneCode: '+359',
    defaultCurrency: 'BGN',
    primaryLanguage: 'bg',
    flagEmoji: '🇧🇬',
    isEu: true,
    isEurozone: false,
    isSchengen: true, // Air/sea Schengen 2024
    isActive: true,
    sortOrder: 24,
  },
  {
    code: 'RS',
    alpha3: 'SRB',
    numericCode: '688',
    nameEn: 'Serbia',
    nameHu: 'Szerbia',
    nameDe: 'Serbien',
    nameNative: 'Србија',
    continent: 'Europe',
    subRegion: 'Southern Europe',
    phoneCode: '+381',
    defaultCurrency: 'RSD',
    primaryLanguage: 'sr',
    flagEmoji: '🇷🇸',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 25,
  },
  {
    code: 'BA',
    alpha3: 'BIH',
    numericCode: '070',
    nameEn: 'Bosnia and Herzegovina',
    nameHu: 'Bosznia-Hercegovina',
    nameDe: 'Bosnien und Herzegowina',
    nameNative: 'Bosna i Hercegovina',
    continent: 'Europe',
    subRegion: 'Southern Europe',
    phoneCode: '+387',
    defaultCurrency: 'BAM',
    primaryLanguage: 'bs',
    flagEmoji: '🇧🇦',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 26,
  },
  {
    code: 'ME',
    alpha3: 'MNE',
    numericCode: '499',
    nameEn: 'Montenegro',
    nameHu: 'Montenegró',
    nameDe: 'Montenegro',
    nameNative: 'Crna Gora',
    continent: 'Europe',
    subRegion: 'Southern Europe',
    phoneCode: '+382',
    defaultCurrency: 'EUR',
    primaryLanguage: 'sr',
    flagEmoji: '🇲🇪',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 27,
  },
  {
    code: 'MK',
    alpha3: 'MKD',
    numericCode: '807',
    nameEn: 'North Macedonia',
    nameHu: 'Észak-Macedónia',
    nameDe: 'Nordmazedonien',
    nameNative: 'Северна Македонија',
    continent: 'Europe',
    subRegion: 'Southern Europe',
    phoneCode: '+389',
    defaultCurrency: 'MKD',
    primaryLanguage: 'mk',
    flagEmoji: '🇲🇰',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 28,
  },
  {
    code: 'AL',
    alpha3: 'ALB',
    numericCode: '008',
    nameEn: 'Albania',
    nameHu: 'Albánia',
    nameDe: 'Albanien',
    nameNative: 'Shqipëria',
    continent: 'Europe',
    subRegion: 'Southern Europe',
    phoneCode: '+355',
    defaultCurrency: 'ALL',
    primaryLanguage: 'sq',
    flagEmoji: '🇦🇱',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 29,
  },
  {
    code: 'GR',
    alpha3: 'GRC',
    numericCode: '300',
    nameEn: 'Greece',
    nameHu: 'Görögország',
    nameDe: 'Griechenland',
    nameNative: 'Ελλάδα',
    continent: 'Europe',
    subRegion: 'Southern Europe',
    phoneCode: '+30',
    defaultCurrency: 'EUR',
    primaryLanguage: 'el',
    flagEmoji: '🇬🇷',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    isActive: true,
    sortOrder: 30,
  },
  {
    code: 'LT',
    alpha3: 'LTU',
    numericCode: '440',
    nameEn: 'Lithuania',
    nameHu: 'Litvánia',
    nameDe: 'Litauen',
    nameNative: 'Lietuva',
    continent: 'Europe',
    subRegion: 'Northern Europe',
    phoneCode: '+370',
    defaultCurrency: 'EUR',
    primaryLanguage: 'lt',
    flagEmoji: '🇱🇹',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    isActive: true,
    sortOrder: 31,
  },
  {
    code: 'LV',
    alpha3: 'LVA',
    numericCode: '428',
    nameEn: 'Latvia',
    nameHu: 'Lettország',
    nameDe: 'Lettland',
    nameNative: 'Latvija',
    continent: 'Europe',
    subRegion: 'Northern Europe',
    phoneCode: '+371',
    defaultCurrency: 'EUR',
    primaryLanguage: 'lv',
    flagEmoji: '🇱🇻',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    isActive: true,
    sortOrder: 32,
  },
  {
    code: 'EE',
    alpha3: 'EST',
    numericCode: '233',
    nameEn: 'Estonia',
    nameHu: 'Észtország',
    nameDe: 'Estland',
    nameNative: 'Eesti',
    continent: 'Europe',
    subRegion: 'Northern Europe',
    phoneCode: '+372',
    defaultCurrency: 'EUR',
    primaryLanguage: 'et',
    flagEmoji: '🇪🇪',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    isActive: true,
    sortOrder: 33,
  },
  {
    code: 'LU',
    alpha3: 'LUX',
    numericCode: '442',
    nameEn: 'Luxembourg',
    nameHu: 'Luxemburg',
    nameDe: 'Luxemburg',
    nameNative: 'Lëtzebuerg',
    continent: 'Europe',
    subRegion: 'Western Europe',
    phoneCode: '+352',
    defaultCurrency: 'EUR',
    primaryLanguage: 'fr',
    flagEmoji: '🇱🇺',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    isActive: true,
    sortOrder: 34,
  },
  {
    code: 'MT',
    alpha3: 'MLT',
    numericCode: '470',
    nameEn: 'Malta',
    nameHu: 'Málta',
    nameDe: 'Malta',
    nameNative: 'Malta',
    continent: 'Europe',
    subRegion: 'Southern Europe',
    phoneCode: '+356',
    defaultCurrency: 'EUR',
    primaryLanguage: 'mt',
    flagEmoji: '🇲🇹',
    isEu: true,
    isEurozone: true,
    isSchengen: true,
    isActive: true,
    sortOrder: 35,
  },
  {
    code: 'CY',
    alpha3: 'CYP',
    numericCode: '196',
    nameEn: 'Cyprus',
    nameHu: 'Ciprus',
    nameDe: 'Zypern',
    nameNative: 'Κύπρος',
    continent: 'Europe',
    subRegion: 'Southern Europe',
    phoneCode: '+357',
    defaultCurrency: 'EUR',
    primaryLanguage: 'el',
    flagEmoji: '🇨🇾',
    isEu: true,
    isEurozone: true,
    isSchengen: false,
    isActive: true,
    sortOrder: 36,
  },
  {
    code: 'UA',
    alpha3: 'UKR',
    numericCode: '804',
    nameEn: 'Ukraine',
    nameHu: 'Ukrajna',
    nameDe: 'Ukraine',
    nameNative: 'Україна',
    continent: 'Europe',
    subRegion: 'Eastern Europe',
    phoneCode: '+380',
    defaultCurrency: 'UAH',
    primaryLanguage: 'uk',
    flagEmoji: '🇺🇦',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 37,
  },
  {
    code: 'BY',
    alpha3: 'BLR',
    numericCode: '112',
    nameEn: 'Belarus',
    nameHu: 'Fehéroroszország',
    nameDe: 'Belarus',
    nameNative: 'Беларусь',
    continent: 'Europe',
    subRegion: 'Eastern Europe',
    phoneCode: '+375',
    defaultCurrency: 'BYN',
    primaryLanguage: 'be',
    flagEmoji: '🇧🇾',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: false,
    sortOrder: 38,
  },
  {
    code: 'MD',
    alpha3: 'MDA',
    numericCode: '498',
    nameEn: 'Moldova',
    nameHu: 'Moldova',
    nameDe: 'Moldau',
    nameNative: 'Moldova',
    continent: 'Europe',
    subRegion: 'Eastern Europe',
    phoneCode: '+373',
    defaultCurrency: 'MDL',
    primaryLanguage: 'ro',
    flagEmoji: '🇲🇩',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 39,
  },

  // ── Adventure Destinations Worldwide ──────────────────────────────────
  {
    code: 'US',
    alpha3: 'USA',
    numericCode: '840',
    nameEn: 'United States',
    nameHu: 'Egyesült Államok',
    nameDe: 'Vereinigte Staaten',
    nameNative: 'United States',
    continent: 'North America',
    subRegion: 'Northern America',
    phoneCode: '+1',
    defaultCurrency: 'USD',
    primaryLanguage: 'en',
    flagEmoji: '🇺🇸',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 40,
  },
  {
    code: 'CA',
    alpha3: 'CAN',
    numericCode: '124',
    nameEn: 'Canada',
    nameHu: 'Kanada',
    nameDe: 'Kanada',
    nameNative: 'Canada',
    continent: 'North America',
    subRegion: 'Northern America',
    phoneCode: '+1',
    defaultCurrency: 'CAD',
    primaryLanguage: 'en',
    flagEmoji: '🇨🇦',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 41,
  },
  {
    code: 'NZ',
    alpha3: 'NZL',
    numericCode: '554',
    nameEn: 'New Zealand',
    nameHu: 'Új-Zéland',
    nameDe: 'Neuseeland',
    nameNative: 'New Zealand',
    continent: 'Oceania',
    subRegion: 'Australasia',
    phoneCode: '+64',
    defaultCurrency: 'NZD',
    primaryLanguage: 'en',
    flagEmoji: '🇳🇿',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 42,
  },
  {
    code: 'AU',
    alpha3: 'AUS',
    numericCode: '036',
    nameEn: 'Australia',
    nameHu: 'Ausztrália',
    nameDe: 'Australien',
    nameNative: 'Australia',
    continent: 'Oceania',
    subRegion: 'Australasia',
    phoneCode: '+61',
    defaultCurrency: 'AUD',
    primaryLanguage: 'en',
    flagEmoji: '🇦🇺',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 43,
  },
  {
    code: 'JP',
    alpha3: 'JPN',
    numericCode: '392',
    nameEn: 'Japan',
    nameHu: 'Japán',
    nameDe: 'Japan',
    nameNative: '日本',
    continent: 'Asia',
    subRegion: 'Eastern Asia',
    phoneCode: '+81',
    defaultCurrency: 'JPY',
    primaryLanguage: 'ja',
    flagEmoji: '🇯🇵',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 44,
  },
  {
    code: 'TH',
    alpha3: 'THA',
    numericCode: '764',
    nameEn: 'Thailand',
    nameHu: 'Thaiföld',
    nameDe: 'Thailand',
    nameNative: 'ประเทศไทย',
    continent: 'Asia',
    subRegion: 'South-Eastern Asia',
    phoneCode: '+66',
    defaultCurrency: 'THB',
    primaryLanguage: 'th',
    flagEmoji: '🇹🇭',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 45,
  },
  {
    code: 'NP',
    alpha3: 'NPL',
    numericCode: '524',
    nameEn: 'Nepal',
    nameHu: 'Nepál',
    nameDe: 'Nepal',
    nameNative: 'नेपाल',
    continent: 'Asia',
    subRegion: 'Southern Asia',
    phoneCode: '+977',
    defaultCurrency: 'NPR',
    primaryLanguage: 'ne',
    flagEmoji: '🇳🇵',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 46,
  },
  {
    code: 'PE',
    alpha3: 'PER',
    numericCode: '604',
    nameEn: 'Peru',
    nameHu: 'Peru',
    nameDe: 'Peru',
    nameNative: 'Perú',
    continent: 'South America',
    subRegion: 'South America',
    phoneCode: '+51',
    defaultCurrency: 'PEN',
    primaryLanguage: 'es',
    flagEmoji: '🇵🇪',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 47,
  },
  {
    code: 'AR',
    alpha3: 'ARG',
    numericCode: '032',
    nameEn: 'Argentina',
    nameHu: 'Argentína',
    nameDe: 'Argentinien',
    nameNative: 'Argentina',
    continent: 'South America',
    subRegion: 'South America',
    phoneCode: '+54',
    defaultCurrency: 'ARS',
    primaryLanguage: 'es',
    flagEmoji: '🇦🇷',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 48,
  },
  {
    code: 'CL',
    alpha3: 'CHL',
    numericCode: '152',
    nameEn: 'Chile',
    nameHu: 'Chile',
    nameDe: 'Chile',
    nameNative: 'Chile',
    continent: 'South America',
    subRegion: 'South America',
    phoneCode: '+56',
    defaultCurrency: 'CLP',
    primaryLanguage: 'es',
    flagEmoji: '🇨🇱',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 49,
  },
  {
    code: 'ZA',
    alpha3: 'ZAF',
    numericCode: '710',
    nameEn: 'South Africa',
    nameHu: 'Dél-Afrika',
    nameDe: 'Südafrika',
    nameNative: 'South Africa',
    continent: 'Africa',
    subRegion: 'Southern Africa',
    phoneCode: '+27',
    defaultCurrency: 'ZAR',
    primaryLanguage: 'en',
    flagEmoji: '🇿🇦',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 50,
  },
  {
    code: 'MA',
    alpha3: 'MAR',
    numericCode: '504',
    nameEn: 'Morocco',
    nameHu: 'Marokkó',
    nameDe: 'Marokko',
    nameNative: 'المغرب',
    continent: 'Africa',
    subRegion: 'Northern Africa',
    phoneCode: '+212',
    defaultCurrency: 'MAD',
    primaryLanguage: 'ar',
    flagEmoji: '🇲🇦',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 51,
  },
  {
    code: 'GE',
    alpha3: 'GEO',
    numericCode: '268',
    nameEn: 'Georgia',
    nameHu: 'Grúzia',
    nameDe: 'Georgien',
    nameNative: 'საქართველო',
    continent: 'Asia',
    subRegion: 'Western Asia',
    phoneCode: '+995',
    defaultCurrency: 'GEL',
    primaryLanguage: 'ka',
    flagEmoji: '🇬🇪',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 52,
  },
  {
    code: 'TR',
    alpha3: 'TUR',
    numericCode: '792',
    nameEn: 'Turkey',
    nameHu: 'Törökország',
    nameDe: 'Türkei',
    nameNative: 'Türkiye',
    continent: 'Asia',
    subRegion: 'Western Asia',
    phoneCode: '+90',
    defaultCurrency: 'TRY',
    primaryLanguage: 'tr',
    flagEmoji: '🇹🇷',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 53,
  },
  {
    code: 'IL',
    alpha3: 'ISR',
    numericCode: '376',
    nameEn: 'Israel',
    nameHu: 'Izrael',
    nameDe: 'Israel',
    nameNative: 'ישראל',
    continent: 'Asia',
    subRegion: 'Western Asia',
    phoneCode: '+972',
    defaultCurrency: 'ILS',
    primaryLanguage: 'he',
    flagEmoji: '🇮🇱',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 54,
  },
  {
    code: 'AE',
    alpha3: 'ARE',
    numericCode: '784',
    nameEn: 'United Arab Emirates',
    nameHu: 'Egyesült Arab Emírségek',
    nameDe: 'Vereinigte Arabische Emirate',
    nameNative: 'الإمارات العربية المتحدة',
    continent: 'Asia',
    subRegion: 'Western Asia',
    phoneCode: '+971',
    defaultCurrency: 'AED',
    primaryLanguage: 'ar',
    flagEmoji: '🇦🇪',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 55,
  },
  {
    code: 'IN',
    alpha3: 'IND',
    numericCode: '356',
    nameEn: 'India',
    nameHu: 'India',
    nameDe: 'Indien',
    nameNative: 'भारत',
    continent: 'Asia',
    subRegion: 'Southern Asia',
    phoneCode: '+91',
    defaultCurrency: 'INR',
    primaryLanguage: 'hi',
    flagEmoji: '🇮🇳',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 56,
  },
  {
    code: 'MX',
    alpha3: 'MEX',
    numericCode: '484',
    nameEn: 'Mexico',
    nameHu: 'Mexikó',
    nameDe: 'Mexiko',
    nameNative: 'México',
    continent: 'North America',
    subRegion: 'Central America',
    phoneCode: '+52',
    defaultCurrency: 'MXN',
    primaryLanguage: 'es',
    flagEmoji: '🇲🇽',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 57,
  },
  {
    code: 'CO',
    alpha3: 'COL',
    numericCode: '170',
    nameEn: 'Colombia',
    nameHu: 'Kolumbia',
    nameDe: 'Kolumbien',
    nameNative: 'Colombia',
    continent: 'South America',
    subRegion: 'South America',
    phoneCode: '+57',
    defaultCurrency: 'COP',
    primaryLanguage: 'es',
    flagEmoji: '🇨🇴',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 58,
  },
  {
    code: 'CR',
    alpha3: 'CRI',
    numericCode: '188',
    nameEn: 'Costa Rica',
    nameHu: 'Costa Rica',
    nameDe: 'Costa Rica',
    nameNative: 'Costa Rica',
    continent: 'North America',
    subRegion: 'Central America',
    phoneCode: '+506',
    defaultCurrency: 'CRC',
    primaryLanguage: 'es',
    flagEmoji: '🇨🇷',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 59,
  },
  {
    code: 'EC',
    alpha3: 'ECU',
    numericCode: '218',
    nameEn: 'Ecuador',
    nameHu: 'Ecuador',
    nameDe: 'Ecuador',
    nameNative: 'Ecuador',
    continent: 'South America',
    subRegion: 'South America',
    phoneCode: '+593',
    defaultCurrency: 'USD',
    primaryLanguage: 'es',
    flagEmoji: '🇪🇨',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 60,
  },
  {
    code: 'KE',
    alpha3: 'KEN',
    numericCode: '404',
    nameEn: 'Kenya',
    nameHu: 'Kenya',
    nameDe: 'Kenia',
    nameNative: 'Kenya',
    continent: 'Africa',
    subRegion: 'Eastern Africa',
    phoneCode: '+254',
    defaultCurrency: 'KES',
    primaryLanguage: 'en',
    flagEmoji: '🇰🇪',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 61,
  },
  {
    code: 'TZ',
    alpha3: 'TZA',
    numericCode: '834',
    nameEn: 'Tanzania',
    nameHu: 'Tanzánia',
    nameDe: 'Tansania',
    nameNative: 'Tanzania',
    continent: 'Africa',
    subRegion: 'Eastern Africa',
    phoneCode: '+255',
    defaultCurrency: 'TZS',
    primaryLanguage: 'sw',
    flagEmoji: '🇹🇿',
    isEu: false,
    isEurozone: false,
    isSchengen: false,
    isActive: true,
    sortOrder: 62,
  },
];

// ============================================================================
// 2. LANGUAGES — ISO 639-1
// ============================================================================

export const languagesData: LanguageSeed[] = [
  // ── App-supported languages (is_app_supported = true) ─────────────────
  {
    code: 'hu',
    nameEn: 'Hungarian',
    nameHu: 'Magyar',
    nameNative: 'Magyar',
    direction: 'ltr',
    isAppSupported: true,
    isContentLanguage: true,
    sortOrder: 1,
    isActive: true,
  },
  {
    code: 'en',
    nameEn: 'English',
    nameHu: 'Angol',
    nameNative: 'English',
    direction: 'ltr',
    isAppSupported: true,
    isContentLanguage: true,
    sortOrder: 2,
    isActive: true,
  },
  {
    code: 'de',
    nameEn: 'German',
    nameHu: 'Német',
    nameNative: 'Deutsch',
    direction: 'ltr',
    isAppSupported: true,
    isContentLanguage: true,
    sortOrder: 3,
    isActive: true,
  },
  {
    code: 'sk',
    nameEn: 'Slovak',
    nameHu: 'Szlovák',
    nameNative: 'Slovenčina',
    direction: 'ltr',
    isAppSupported: true,
    isContentLanguage: true,
    sortOrder: 4,
    isActive: true,
  },
  {
    code: 'hr',
    nameEn: 'Croatian',
    nameHu: 'Horvát',
    nameNative: 'Hrvatski',
    direction: 'ltr',
    isAppSupported: true,
    isContentLanguage: true,
    sortOrder: 5,
    isActive: true,
  },
  {
    code: 'sl',
    nameEn: 'Slovenian',
    nameHu: 'Szlovén',
    nameNative: 'Slovenščina',
    direction: 'ltr',
    isAppSupported: true,
    isContentLanguage: true,
    sortOrder: 6,
    isActive: true,
  },
  {
    code: 'ro',
    nameEn: 'Romanian',
    nameHu: 'Román',
    nameNative: 'Română',
    direction: 'ltr',
    isAppSupported: true,
    isContentLanguage: true,
    sortOrder: 7,
    isActive: true,
  },
  {
    code: 'cs',
    nameEn: 'Czech',
    nameHu: 'Cseh',
    nameNative: 'Čeština',
    direction: 'ltr',
    isAppSupported: true,
    isContentLanguage: true,
    sortOrder: 8,
    isActive: true,
  },

  // ── Content languages ─────────────────────────────────────────────────
  {
    code: 'fr',
    nameEn: 'French',
    nameHu: 'Francia',
    nameNative: 'Français',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 9,
    isActive: true,
  },
  {
    code: 'es',
    nameEn: 'Spanish',
    nameHu: 'Spanyol',
    nameNative: 'Español',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 10,
    isActive: true,
  },
  {
    code: 'it',
    nameEn: 'Italian',
    nameHu: 'Olasz',
    nameNative: 'Italiano',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 11,
    isActive: true,
  },
  {
    code: 'pt',
    nameEn: 'Portuguese',
    nameHu: 'Portugál',
    nameNative: 'Português',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 12,
    isActive: true,
  },
  {
    code: 'nl',
    nameEn: 'Dutch',
    nameHu: 'Holland',
    nameNative: 'Nederlands',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 13,
    isActive: true,
  },
  {
    code: 'pl',
    nameEn: 'Polish',
    nameHu: 'Lengyel',
    nameNative: 'Polski',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 14,
    isActive: true,
  },
  {
    code: 'sv',
    nameEn: 'Swedish',
    nameHu: 'Svéd',
    nameNative: 'Svenska',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 15,
    isActive: true,
  },
  {
    code: 'no',
    nameEn: 'Norwegian',
    nameHu: 'Norvég',
    nameNative: 'Norsk',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 16,
    isActive: true,
  },
  {
    code: 'da',
    nameEn: 'Danish',
    nameHu: 'Dán',
    nameNative: 'Dansk',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 17,
    isActive: true,
  },
  {
    code: 'fi',
    nameEn: 'Finnish',
    nameHu: 'Finn',
    nameNative: 'Suomi',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 18,
    isActive: true,
  },
  {
    code: 'bg',
    nameEn: 'Bulgarian',
    nameHu: 'Bolgár',
    nameNative: 'Български',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 19,
    isActive: true,
  },
  {
    code: 'sr',
    nameEn: 'Serbian',
    nameHu: 'Szerb',
    nameNative: 'Српски',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 20,
    isActive: true,
  },
  {
    code: 'el',
    nameEn: 'Greek',
    nameHu: 'Görög',
    nameNative: 'Ελληνικά',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 21,
    isActive: true,
  },
  {
    code: 'tr',
    nameEn: 'Turkish',
    nameHu: 'Török',
    nameNative: 'Türkçe',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 22,
    isActive: true,
  },
  {
    code: 'ja',
    nameEn: 'Japanese',
    nameHu: 'Japán',
    nameNative: '日本語',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 23,
    isActive: true,
  },
  {
    code: 'th',
    nameEn: 'Thai',
    nameHu: 'Thai',
    nameNative: 'ไทย',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 24,
    isActive: true,
  },
  {
    code: 'ar',
    nameEn: 'Arabic',
    nameHu: 'Arab',
    nameNative: 'العربية',
    direction: 'rtl',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 25,
    isActive: true,
  },
  {
    code: 'he',
    nameEn: 'Hebrew',
    nameHu: 'Héber',
    nameNative: 'עברית',
    direction: 'rtl',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 26,
    isActive: true,
  },
  {
    code: 'uk',
    nameEn: 'Ukrainian',
    nameHu: 'Ukrán',
    nameNative: 'Українська',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 27,
    isActive: true,
  },
  {
    code: 'ru',
    nameEn: 'Russian',
    nameHu: 'Orosz',
    nameNative: 'Русский',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 28,
    isActive: true,
  },
  {
    code: 'ka',
    nameEn: 'Georgian',
    nameHu: 'Grúz',
    nameNative: 'ქართული',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 29,
    isActive: true,
  },
  {
    code: 'ne',
    nameEn: 'Nepali',
    nameHu: 'Nepáli',
    nameNative: 'नेपाली',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 30,
    isActive: true,
  },
  {
    code: 'ko',
    nameEn: 'Korean',
    nameHu: 'Koreai',
    nameNative: '한국어',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 31,
    isActive: true,
  },
  {
    code: 'zh',
    nameEn: 'Chinese',
    nameHu: 'Kínai',
    nameNative: '中文',
    direction: 'ltr',
    isAppSupported: false,
    isContentLanguage: true,
    sortOrder: 32,
    isActive: true,
  },
];

// ============================================================================
// 3. CURRENCIES — ISO 4217
// ============================================================================

export const currenciesData: CurrencySeed[] = [
  {
    code: 'EUR',
    numericCode: '978',
    nameEn: 'Euro',
    nameHu: 'Euró',
    symbol: '€',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: '€1,234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    code: 'HUF',
    numericCode: '348',
    nameEn: 'Hungarian Forint',
    nameHu: 'Magyar forint',
    symbol: 'Ft',
    decimalDigits: 0,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1 234 Ft',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    code: 'CZK',
    numericCode: '203',
    nameEn: 'Czech Koruna',
    nameHu: 'Cseh korona',
    symbol: 'Kč',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1 234,56 Kč',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    code: 'HRK',
    numericCode: '191',
    nameEn: 'Croatian Kuna',
    nameHu: 'Horvát kuna',
    symbol: 'kn',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1.234,56 kn',
    isStripeSupported: false,
    isActive: false, // Legacy — Croatia adopted EUR in 2023
    sortOrder: 4,
  },
  {
    code: 'RON',
    numericCode: '946',
    nameEn: 'Romanian Leu',
    nameHu: 'Román lej',
    symbol: 'lei',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1.234,56 lei',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 5,
  },
  {
    code: 'PLN',
    numericCode: '985',
    nameEn: 'Polish Zloty',
    nameHu: 'Lengyel złoty',
    symbol: 'zł',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1 234,56 zł',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 6,
  },
  {
    code: 'GBP',
    numericCode: '826',
    nameEn: 'British Pound Sterling',
    nameHu: 'Brit font',
    symbol: '£',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: '£1,234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 7,
  },
  {
    code: 'CHF',
    numericCode: '756',
    nameEn: 'Swiss Franc',
    nameHu: 'Svájci frank',
    symbol: 'CHF',
    decimalDigits: 2,
    thousandsSeparator: "'",
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: "CHF 1'234.56",
    isStripeSupported: true,
    isActive: true,
    sortOrder: 8,
  },
  {
    code: 'SEK',
    numericCode: '752',
    nameEn: 'Swedish Krona',
    nameHu: 'Svéd korona',
    symbol: 'kr',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1 234,56 kr',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 9,
  },
  {
    code: 'NOK',
    numericCode: '578',
    nameEn: 'Norwegian Krone',
    nameHu: 'Norvég korona',
    symbol: 'kr',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1 234,56 kr',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 10,
  },
  {
    code: 'DKK',
    numericCode: '208',
    nameEn: 'Danish Krone',
    nameHu: 'Dán korona',
    symbol: 'kr',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1.234,56 kr',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 11,
  },
  {
    code: 'BGN',
    numericCode: '975',
    nameEn: 'Bulgarian Lev',
    nameHu: 'Bolgár leva',
    symbol: 'лв',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1 234,56 лв',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 12,
  },
  {
    code: 'RSD',
    numericCode: '941',
    nameEn: 'Serbian Dinar',
    nameHu: 'Szerb dinár',
    symbol: 'din.',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1.234,56 din.',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 13,
  },
  {
    code: 'BAM',
    numericCode: '977',
    nameEn: 'Bosnia-Herzegovina Convertible Mark',
    nameHu: 'Bosnyák konvertibilis márka',
    symbol: 'KM',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1.234,56 KM',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 14,
  },
  {
    code: 'MKD',
    numericCode: '807',
    nameEn: 'Macedonian Denar',
    nameHu: 'Macedón dénár',
    symbol: 'ден',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1.234,56 ден',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 15,
  },
  {
    code: 'ALL',
    numericCode: '008',
    nameEn: 'Albanian Lek',
    nameHu: 'Albán lek',
    symbol: 'L',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1 234,56 L',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 16,
  },
  {
    code: 'ISK',
    numericCode: '352',
    nameEn: 'Icelandic Krona',
    nameHu: 'Izlandi korona',
    symbol: 'kr',
    decimalDigits: 0,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1.234 kr',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 17,
  },
  {
    code: 'TRY',
    numericCode: '949',
    nameEn: 'Turkish Lira',
    nameHu: 'Török líra',
    symbol: '₺',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'prefix',
    formatExample: '₺1.234,56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 18,
  },
  {
    code: 'USD',
    numericCode: '840',
    nameEn: 'US Dollar',
    nameHu: 'Amerikai dollár',
    symbol: '$',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: '$1,234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 19,
  },
  {
    code: 'CAD',
    numericCode: '124',
    nameEn: 'Canadian Dollar',
    nameHu: 'Kanadai dollár',
    symbol: 'CA$',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: 'CA$1,234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 20,
  },
  {
    code: 'AUD',
    numericCode: '036',
    nameEn: 'Australian Dollar',
    nameHu: 'Ausztrál dollár',
    symbol: 'A$',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: 'A$1,234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 21,
  },
  {
    code: 'NZD',
    numericCode: '554',
    nameEn: 'New Zealand Dollar',
    nameHu: 'Új-zélandi dollár',
    symbol: 'NZ$',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: 'NZ$1,234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 22,
  },
  {
    code: 'JPY',
    numericCode: '392',
    nameEn: 'Japanese Yen',
    nameHu: 'Japán jen',
    symbol: '¥',
    decimalDigits: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: '¥1,234',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 23,
  },
  {
    code: 'THB',
    numericCode: '764',
    nameEn: 'Thai Baht',
    nameHu: 'Thai baht',
    symbol: '฿',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: '฿1,234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 24,
  },
  {
    code: 'INR',
    numericCode: '356',
    nameEn: 'Indian Rupee',
    nameHu: 'Indiai rúpia',
    symbol: '₹',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: '₹1,234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 25,
  },
  {
    code: 'AED',
    numericCode: '784',
    nameEn: 'UAE Dirham',
    nameHu: 'Emirátusi dirham',
    symbol: 'د.إ',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: 'د.إ1,234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 26,
  },
  {
    code: 'ILS',
    numericCode: '376',
    nameEn: 'Israeli New Shekel',
    nameHu: 'Izraeli sékel',
    symbol: '₪',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: '₪1,234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 27,
  },
  {
    code: 'ZAR',
    numericCode: '710',
    nameEn: 'South African Rand',
    nameHu: 'Dél-afrikai rand',
    symbol: 'R',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: 'R 1 234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 28,
  },
  {
    code: 'MXN',
    numericCode: '484',
    nameEn: 'Mexican Peso',
    nameHu: 'Mexikói peso',
    symbol: 'MX$',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: 'MX$1,234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 29,
  },
  {
    code: 'BRL',
    numericCode: '986',
    nameEn: 'Brazilian Real',
    nameHu: 'Brazil real',
    symbol: 'R$',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'prefix',
    formatExample: 'R$1.234,56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 30,
  },
  {
    code: 'GEL',
    numericCode: '981',
    nameEn: 'Georgian Lari',
    nameHu: 'Grúz lari',
    symbol: '₾',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    symbolPosition: 'suffix',
    formatExample: '1 234,56 ₾',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 31,
  },
  {
    code: 'NPR',
    numericCode: '524',
    nameEn: 'Nepalese Rupee',
    nameHu: 'Nepáli rúpia',
    symbol: 'रू',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: 'रू1,234.56',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 32,
  },
  {
    code: 'PEN',
    numericCode: '604',
    nameEn: 'Peruvian Sol',
    nameHu: 'Perui sol',
    symbol: 'S/',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: 'S/1,234.56',
    isStripeSupported: true,
    isActive: true,
    sortOrder: 33,
  },
  {
    code: 'ARS',
    numericCode: '032',
    nameEn: 'Argentine Peso',
    nameHu: 'Argentin peso',
    symbol: 'AR$',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'prefix',
    formatExample: 'AR$1.234,56',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 34,
  },
  {
    code: 'CLP',
    numericCode: '152',
    nameEn: 'Chilean Peso',
    nameHu: 'Chilei peso',
    symbol: 'CL$',
    decimalDigits: 0,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'prefix',
    formatExample: 'CL$1.234',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 35,
  },
  {
    code: 'COP',
    numericCode: '170',
    nameEn: 'Colombian Peso',
    nameHu: 'Kolumbiai peso',
    symbol: 'CO$',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'prefix',
    formatExample: 'CO$1.234,56',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 36,
  },
  {
    code: 'CRC',
    numericCode: '188',
    nameEn: 'Costa Rican Colon',
    nameHu: 'Costa Rica-i colón',
    symbol: '₡',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    symbolPosition: 'prefix',
    formatExample: '₡1.234,56',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 37,
  },
  {
    code: 'KES',
    numericCode: '404',
    nameEn: 'Kenyan Shilling',
    nameHu: 'Kenyai shilling',
    symbol: 'KSh',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: 'KSh1,234.56',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 38,
  },
  {
    code: 'TZS',
    numericCode: '834',
    nameEn: 'Tanzanian Shilling',
    nameHu: 'Tanzániai shilling',
    symbol: 'TSh',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    symbolPosition: 'prefix',
    formatExample: 'TSh1,234.56',
    isStripeSupported: false,
    isActive: true,
    sortOrder: 39,
  },
];

// ============================================================================
// 4. TIMEZONES — IANA
// ============================================================================

export const timezonesData: TimezoneSeed[] = [
  // ── European Timezones ────────────────────────────────────────────────
  {
    tzId: 'Europe/Budapest',
    displayName: 'Budapest (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'HU',
    sortOrder: 1,
    isActive: true,
  },
  {
    tzId: 'Europe/Bratislava',
    displayName: 'Bratislava (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'SK',
    sortOrder: 2,
    isActive: true,
  },
  {
    tzId: 'Europe/Prague',
    displayName: 'Prague (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'CZ',
    sortOrder: 3,
    isActive: true,
  },
  {
    tzId: 'Europe/Zagreb',
    displayName: 'Zagreb (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'HR',
    sortOrder: 4,
    isActive: true,
  },
  {
    tzId: 'Europe/Ljubljana',
    displayName: 'Ljubljana (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'SI',
    sortOrder: 5,
    isActive: true,
  },
  {
    tzId: 'Europe/Bucharest',
    displayName: 'Bucharest (EET/EEST)',
    utcOffsetMinutes: 120,
    utcOffsetText: 'UTC+02:00',
    hasDst: true,
    countryCode: 'RO',
    sortOrder: 6,
    isActive: true,
  },
  {
    tzId: 'Europe/Berlin',
    displayName: 'Berlin (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'DE',
    sortOrder: 7,
    isActive: true,
  },
  {
    tzId: 'Europe/Vienna',
    displayName: 'Vienna (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'AT',
    sortOrder: 8,
    isActive: true,
  },
  {
    tzId: 'Europe/Warsaw',
    displayName: 'Warsaw (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'PL',
    sortOrder: 9,
    isActive: true,
  },
  {
    tzId: 'Europe/Rome',
    displayName: 'Rome (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'IT',
    sortOrder: 10,
    isActive: true,
  },
  {
    tzId: 'Europe/Paris',
    displayName: 'Paris (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'FR',
    sortOrder: 11,
    isActive: true,
  },
  {
    tzId: 'Europe/Madrid',
    displayName: 'Madrid (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'ES',
    sortOrder: 12,
    isActive: true,
  },
  {
    tzId: 'Europe/Lisbon',
    displayName: 'Lisbon (WET/WEST)',
    utcOffsetMinutes: 0,
    utcOffsetText: 'UTC+00:00',
    hasDst: true,
    countryCode: 'PT',
    sortOrder: 13,
    isActive: true,
  },
  {
    tzId: 'Europe/London',
    displayName: 'London (GMT/BST)',
    utcOffsetMinutes: 0,
    utcOffsetText: 'UTC+00:00',
    hasDst: true,
    countryCode: 'GB',
    sortOrder: 14,
    isActive: true,
  },
  {
    tzId: 'Europe/Amsterdam',
    displayName: 'Amsterdam (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'NL',
    sortOrder: 15,
    isActive: true,
  },
  {
    tzId: 'Europe/Brussels',
    displayName: 'Brussels (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'BE',
    sortOrder: 16,
    isActive: true,
  },
  {
    tzId: 'Europe/Stockholm',
    displayName: 'Stockholm (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'SE',
    sortOrder: 17,
    isActive: true,
  },
  {
    tzId: 'Europe/Oslo',
    displayName: 'Oslo (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'NO',
    sortOrder: 18,
    isActive: true,
  },
  {
    tzId: 'Europe/Copenhagen',
    displayName: 'Copenhagen (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'DK',
    sortOrder: 19,
    isActive: true,
  },
  {
    tzId: 'Europe/Helsinki',
    displayName: 'Helsinki (EET/EEST)',
    utcOffsetMinutes: 120,
    utcOffsetText: 'UTC+02:00',
    hasDst: true,
    countryCode: 'FI',
    sortOrder: 20,
    isActive: true,
  },
  {
    tzId: 'Europe/Athens',
    displayName: 'Athens (EET/EEST)',
    utcOffsetMinutes: 120,
    utcOffsetText: 'UTC+02:00',
    hasDst: true,
    countryCode: 'GR',
    sortOrder: 21,
    isActive: true,
  },
  {
    tzId: 'Europe/Istanbul',
    displayName: 'Istanbul (TRT)',
    utcOffsetMinutes: 180,
    utcOffsetText: 'UTC+03:00',
    hasDst: false, // Turkey abolished DST in 2016
    countryCode: 'TR',
    sortOrder: 22,
    isActive: true,
  },
  {
    tzId: 'Europe/Zurich',
    displayName: 'Zurich (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'CH',
    sortOrder: 23,
    isActive: true,
  },
  {
    tzId: 'Europe/Dublin',
    displayName: 'Dublin (GMT/IST)',
    utcOffsetMinutes: 0,
    utcOffsetText: 'UTC+00:00',
    hasDst: true,
    countryCode: 'IE',
    sortOrder: 24,
    isActive: true,
  },
  {
    tzId: 'Atlantic/Reykjavik',
    displayName: 'Reykjavik (GMT)',
    utcOffsetMinutes: 0,
    utcOffsetText: 'UTC+00:00',
    hasDst: false, // Iceland does not observe DST
    countryCode: 'IS',
    sortOrder: 25,
    isActive: true,
  },
  {
    tzId: 'Europe/Sofia',
    displayName: 'Sofia (EET/EEST)',
    utcOffsetMinutes: 120,
    utcOffsetText: 'UTC+02:00',
    hasDst: true,
    countryCode: 'BG',
    sortOrder: 26,
    isActive: true,
  },
  {
    tzId: 'Europe/Belgrade',
    displayName: 'Belgrade (CET/CEST)',
    utcOffsetMinutes: 60,
    utcOffsetText: 'UTC+01:00',
    hasDst: true,
    countryCode: 'RS',
    sortOrder: 27,
    isActive: true,
  },
  {
    tzId: 'Europe/Vilnius',
    displayName: 'Vilnius (EET/EEST)',
    utcOffsetMinutes: 120,
    utcOffsetText: 'UTC+02:00',
    hasDst: true,
    countryCode: 'LT',
    sortOrder: 28,
    isActive: true,
  },
  {
    tzId: 'Europe/Riga',
    displayName: 'Riga (EET/EEST)',
    utcOffsetMinutes: 120,
    utcOffsetText: 'UTC+02:00',
    hasDst: true,
    countryCode: 'LV',
    sortOrder: 29,
    isActive: true,
  },
  {
    tzId: 'Europe/Tallinn',
    displayName: 'Tallinn (EET/EEST)',
    utcOffsetMinutes: 120,
    utcOffsetText: 'UTC+02:00',
    hasDst: true,
    countryCode: 'EE',
    sortOrder: 30,
    isActive: true,
  },
  {
    tzId: 'Europe/Kyiv',
    displayName: 'Kyiv (EET/EEST)',
    utcOffsetMinutes: 120,
    utcOffsetText: 'UTC+02:00',
    hasDst: true,
    countryCode: 'UA',
    sortOrder: 31,
    isActive: true,
  },
  {
    tzId: 'Europe/Chisinau',
    displayName: 'Chisinau (EET/EEST)',
    utcOffsetMinutes: 120,
    utcOffsetText: 'UTC+02:00',
    hasDst: true,
    countryCode: 'MD',
    sortOrder: 32,
    isActive: true,
  },
  {
    tzId: 'Asia/Tbilisi',
    displayName: 'Tbilisi (GET)',
    utcOffsetMinutes: 240,
    utcOffsetText: 'UTC+04:00',
    hasDst: false,
    countryCode: 'GE',
    sortOrder: 33,
    isActive: true,
  },

  // ── World Timezones ───────────────────────────────────────────────────
  {
    tzId: 'America/New_York',
    displayName: 'New York (EST/EDT)',
    utcOffsetMinutes: -300,
    utcOffsetText: 'UTC-05:00',
    hasDst: true,
    countryCode: 'US',
    sortOrder: 34,
    isActive: true,
  },
  {
    tzId: 'America/Chicago',
    displayName: 'Chicago (CST/CDT)',
    utcOffsetMinutes: -360,
    utcOffsetText: 'UTC-06:00',
    hasDst: true,
    countryCode: 'US',
    sortOrder: 35,
    isActive: true,
  },
  {
    tzId: 'America/Denver',
    displayName: 'Denver (MST/MDT)',
    utcOffsetMinutes: -420,
    utcOffsetText: 'UTC-07:00',
    hasDst: true,
    countryCode: 'US',
    sortOrder: 36,
    isActive: true,
  },
  {
    tzId: 'America/Los_Angeles',
    displayName: 'Los Angeles (PST/PDT)',
    utcOffsetMinutes: -480,
    utcOffsetText: 'UTC-08:00',
    hasDst: true,
    countryCode: 'US',
    sortOrder: 37,
    isActive: true,
  },
  {
    tzId: 'America/Toronto',
    displayName: 'Toronto (EST/EDT)',
    utcOffsetMinutes: -300,
    utcOffsetText: 'UTC-05:00',
    hasDst: true,
    countryCode: 'CA',
    sortOrder: 38,
    isActive: true,
  },
  {
    tzId: 'Pacific/Auckland',
    displayName: 'Auckland (NZST/NZDT)',
    utcOffsetMinutes: 720,
    utcOffsetText: 'UTC+12:00',
    hasDst: true,
    countryCode: 'NZ',
    sortOrder: 39,
    isActive: true,
  },
  {
    tzId: 'Australia/Sydney',
    displayName: 'Sydney (AEST/AEDT)',
    utcOffsetMinutes: 600,
    utcOffsetText: 'UTC+10:00',
    hasDst: true,
    countryCode: 'AU',
    sortOrder: 40,
    isActive: true,
  },
  {
    tzId: 'Asia/Tokyo',
    displayName: 'Tokyo (JST)',
    utcOffsetMinutes: 540,
    utcOffsetText: 'UTC+09:00',
    hasDst: false,
    countryCode: 'JP',
    sortOrder: 41,
    isActive: true,
  },
  {
    tzId: 'Asia/Bangkok',
    displayName: 'Bangkok (ICT)',
    utcOffsetMinutes: 420,
    utcOffsetText: 'UTC+07:00',
    hasDst: false,
    countryCode: 'TH',
    sortOrder: 42,
    isActive: true,
  },
  {
    tzId: 'Asia/Kathmandu',
    displayName: 'Kathmandu (NPT)',
    utcOffsetMinutes: 345,
    utcOffsetText: 'UTC+05:45',
    hasDst: false,
    countryCode: 'NP',
    sortOrder: 43,
    isActive: true,
  },
  {
    tzId: 'Asia/Dubai',
    displayName: 'Dubai (GST)',
    utcOffsetMinutes: 240,
    utcOffsetText: 'UTC+04:00',
    hasDst: false,
    countryCode: 'AE',
    sortOrder: 44,
    isActive: true,
  },
  {
    tzId: 'Asia/Jerusalem',
    displayName: 'Jerusalem (IST/IDT)',
    utcOffsetMinutes: 120,
    utcOffsetText: 'UTC+02:00',
    hasDst: true,
    countryCode: 'IL',
    sortOrder: 45,
    isActive: true,
  },
  {
    tzId: 'Asia/Kolkata',
    displayName: 'Kolkata (IST)',
    utcOffsetMinutes: 330,
    utcOffsetText: 'UTC+05:30',
    hasDst: false,
    countryCode: 'IN',
    sortOrder: 46,
    isActive: true,
  },
  {
    tzId: 'Africa/Nairobi',
    displayName: 'Nairobi (EAT)',
    utcOffsetMinutes: 180,
    utcOffsetText: 'UTC+03:00',
    hasDst: false,
    countryCode: 'KE',
    sortOrder: 47,
    isActive: true,
  },
  {
    tzId: 'Africa/Johannesburg',
    displayName: 'Johannesburg (SAST)',
    utcOffsetMinutes: 120,
    utcOffsetText: 'UTC+02:00',
    hasDst: false,
    countryCode: 'ZA',
    sortOrder: 48,
    isActive: true,
  },
  {
    tzId: 'America/Mexico_City',
    displayName: 'Mexico City (CST)',
    utcOffsetMinutes: -360,
    utcOffsetText: 'UTC-06:00',
    hasDst: false, // Mexico abolished DST in 2022
    countryCode: 'MX',
    sortOrder: 49,
    isActive: true,
  },
  {
    tzId: 'America/Lima',
    displayName: 'Lima (PET)',
    utcOffsetMinutes: -300,
    utcOffsetText: 'UTC-05:00',
    hasDst: false,
    countryCode: 'PE',
    sortOrder: 50,
    isActive: true,
  },
  {
    tzId: 'America/Bogota',
    displayName: 'Bogota (COT)',
    utcOffsetMinutes: -300,
    utcOffsetText: 'UTC-05:00',
    hasDst: false,
    countryCode: 'CO',
    sortOrder: 51,
    isActive: true,
  },
  {
    tzId: 'America/Costa_Rica',
    displayName: 'San Jose (CST)',
    utcOffsetMinutes: -360,
    utcOffsetText: 'UTC-06:00',
    hasDst: false,
    countryCode: 'CR',
    sortOrder: 52,
    isActive: true,
  },
  {
    tzId: 'America/Argentina/Buenos_Aires',
    displayName: 'Buenos Aires (ART)',
    utcOffsetMinutes: -180,
    utcOffsetText: 'UTC-03:00',
    hasDst: false,
    countryCode: 'AR',
    sortOrder: 53,
    isActive: true,
  },
  {
    tzId: 'America/Santiago',
    displayName: 'Santiago (CLT/CLST)',
    utcOffsetMinutes: -240,
    utcOffsetText: 'UTC-04:00',
    hasDst: true,
    countryCode: 'CL',
    sortOrder: 54,
    isActive: true,
  },
];
