// M23 Calendar — a Nager.Date angol ünnepneveinek magyar megfelelője (seed-generátor bemenete).
// Hiányzó név esetén a generátor hibával leáll: új ország vagy év betöltésekor itt kell bővíteni.

const WORKERS = "A munka ünnepe";
const ALL_SAINTS = "Mindenszentek";
const ASSUMPTION = "Nagyboldogasszony";
const IMMACULATE = "Szeplőtelen fogantatás";
const NATIVITY_MARY = "Kisboldogasszony";
const CYRIL = "Szent Cirill és Metód napja";
const OCHI = "Ochi-nap (a „nem” napja)";
const CLEAN_MONDAY = "Tiszta hétfő (a nagyböjt kezdete)";

export const HU_HOLIDAY_NAMES = {
  "1848 Revolution Memorial Day": "Nemzeti ünnep (1848. március 15.)",
  "1956 Revolution Memorial Day": "Nemzeti ünnep (1956. október 23.)",
  "All Saints Day": ALL_SAINTS,
  "All Saints' Day": ALL_SAINTS,
  "All Saints’ Day": ALL_SAINTS,
  "All Souls' Day": "Halottak napja",
  "Anniversary of the Arengo": "Az Arengo évfordulója",
  "Anniversary of the election of Pope Francis": "Ferenc pápa megválasztásának évfordulója",
  "Anniversary of the foundation of Vatican City": "A Vatikánvárosi Állam alapításának évfordulója",
  "Annunciation": "Gyümölcsöző Boldogasszony (Angyali üdvözlet)",
  "Anti-Fascist Struggle Day": "Az antifasiszta harc napja",
  "Armistice Day": "A fegyverszünet napja",
  "Ascension Day": "Áldozócsütörtök",
  "Assumption": ASSUMPTION,
  "Assumption Day": ASSUMPTION,
  "Assumption of the Virgin Mary": ASSUMPTION,
  "August Holiday": "Augusztusi munkaszüneti nap",
  "Bastille Day": "Nemzeti ünnep (a Bastille ostroma)",
  "Belgian National Day": "Belgium nemzeti ünnepe",
  "Bălţi Day": "Bălți város napja",
  "Candlemas": "Gyertyaszentelő Boldogasszony",
  "Capital's Day": "A főváros napja",
  "Carnival": "Karnevál",
  "Catholic Christmas Day": "Karácsony (katolikus)",
  "Children's Day": "Gyermeknap",
  "Christmas Day": "Karácsony",
  "Christmas Day (Orthodox)": "Karácsony (ortodox)",
  "Christmas Eve": "Szenteste",
  "Clean Monday": CLEAN_MONDAY,
  "Commemoration Day": "Emléknap",
  "Commemoration of all those who died at war": "A háborúban elesettek emléknapja",
  "Commerce Day": "A kereskedelem napja",
  "Constitution Day": "Az alkotmány napja",
  "Corpus Christi": "Úrnapja",
  "Currency change day": "A pénzváltás napja",
  "Cyprus Independence Day": "Ciprus függetlenségének napja",
  "Cyprus National Day": "Ciprus nemzeti ünnepe",
  "Day after New Year's Day": "Újév másnapja",
  "Day of Our Lady of the Seven Sorrows": "A Hétfájdalmú Szűzanya napja",
  "Day of Restoration of Independence": "A függetlenség visszaállításának napja",
  "Day of Restoration of Independence of Lithuania": "Litvánia függetlensége visszaállításának napja",
  "Day of Uprising Against Occupation": "A megszállás elleni felkelés napja",
  "Day of Veterans of the Armed Forces and Law Enforcement Agencies": "A fegyveres erők és a rendvédelmi szervek veteránjainak napja",
  "Day of the Convocation of the Constitutional Assembly of the Republic of Latvia": "A lett alkotmányozó nemzetgyűlés összehívásának napja",
  "Day of the Dead": "Halottak napja",
  "Day of the Establishment of the Slovak Republic": "A Szlovák Köztársaság megalakulásának napja",
  "Day of the Macedonian Revolutionary Struggle": "A macedón forradalmi harc napja",
  "Day of the Moldovan National Army": "A moldovai nemzeti hadsereg napja",
  "Day of the Proclamation of the Republic of Latvia": "A Lett Köztársaság kikiáltásának napja",
  "Day of the Republic": "A köztársaság napja",
  "Day of the Restoration of Independence of the Republic of Latvia": "A Lett Köztársaság függetlensége visszaállításának napja",
  "Day of victory over fascism": "A fasizmus feletti győzelem napja",
  "Defender of Ukraine Day": "Ukrajna védelmezőinek napja",
  "Defender of the Fatherland Day": "A haza védelmezőinek napja",
  "Dormition of the Theotokos": "Nagyboldogasszony (az Istenszülő elszenderülése)",
  "Early May Bank Holiday": "Május eleji munkaszüneti nap",
  "Easter Monday": "Húsvéthétfő",
  "Easter Sunday": "Húsvétvasárnap",
  "Epiphany": "Vízkereszt",
  "Europe Day": "Európa-nap",
  "Feast of Our Lady of Victories": "A Győzelmes Boldogasszony ünnepe",
  "Feast of Saint Agatha": "Szent Ágota ünnepe",
  "Feast of St. Joseph": "Szent József ünnepe",
  "Feast of St. Paul's Shipwreck": "Szent Pál hajótörésének ünnepe",
  "Feast of St.Peter and St.Paul": "Szent Péter és Szent Pál ünnepe",
  "Feast of the Immaculate Conception": IMMACULATE,
  "Ferragosto (Assumption)": ASSUMPTION,
  "Final Day of the Nationwide Latvian Song and Dance Celebration": "Az országos lett dal- és táncünnep zárónapja",
  "First Day of Summer": "A nyár első napja",
  "Freedom Day": "A szabadság napja",
  "German Unity Day": "A német egység napja",
  "Good Friday": "Nagypéntek",
  "Greek Independence Day": "Görögország függetlenségének napja",
  "Green Monday": CLEAN_MONDAY,
  "Holy Saturday": "Nagyszombat",
  "Icelandic National Day": "Izland nemzeti ünnepe",
  "Immaculate Conception": IMMACULATE,
  "Independence Day": "A függetlenség napja",
  "Independence Day (Moldova)": "A függetlenség napja",
  "Independence and Unity Day": "A függetlenség és az egység napja",
  "Independent Czechoslovak State Day": "A független csehszlovák állam megalakulásának napja",
  "International Women's Day": "Nemzetközi nőnap",
  "International Workers Day": WORKERS,
  "International Workers' Day": WORKERS,
  "International Working Day": WORKERS,
  "Jan Hus Day": "Husz János máglyahalálának napja",
  "June Holiday": "Júniusi munkaszüneti nap",
  "Jāņi Day": "Szent Iván-nap (Jāņi)",
  "King's Day": "A király napja",
  "Labour Day": WORKERS,
  "Labour Day (Moldova)": WORKERS,
  "Labour day": WORKERS,
  "Liberation Day": "A felszabadulás napja",
  "Liberation from Fascism": "A fasizmus alóli felszabadulás napja",
  "Limba Noastra (National Language Day)": "A nemzeti nyelv napja (Limba noastră)",
  "Līgo Day": "Szent Iván-nap előestéje (Līgo)",
  "Maundy Thursday": "Nagycsütörtök",
  "May Day": WORKERS,
  "May Day / International Workers' Day": WORKERS,
  "Memorial Day": "Emléknap",
  "Midsummer Day": "Szent Iván-nap",
  "Midsummer Eve": "Szent Iván-éj",
  "Mother Teresa Day": "Teréz anya napja",
  "Mother's Day": "Anyák napja",
  "National Day": "Nemzeti ünnep",
  "National Day of Spain": "Spanyolország nemzeti ünnepe",
  "National Day of Sweden": "Svédország nemzeti ünnepe",
  "National Day/Great Union": "Nemzeti ünnep (a nagy egyesülés napja)",
  "National Holiday": "Nemzeti ünnep",
  "Nativity of Mary": NATIVITY_MARY,
  "Nativity of Our Lady": NATIVITY_MARY,
  "New Year holiday": "Újévi munkaszüneti nap",
  "New Year's Day": "Újév",
  "New Year's Eve": "Szilveszter",
  "Nowruz": "Nevruz (tavaszi újév)",
  "Ochi Day": OCHI,
  "October Holiday": "Októberi munkaszüneti nap",
  "October Revolution Day": "Az októberi forradalom napja",
  "Ohi Day": OCHI,
  "Pentecost": "Pünkösdvasárnap",
  "Prešeren Day": "Prešeren-nap (a szlovén kultúra napja)",
  "Reformation Day": "A reformáció napja",
  "Remembrance Day": "Emléknap",
  "Republic Day": "A köztársaság napja",
  "Restoration of Independence": "A függetlenség visszaállításának napja",
  "Revolution Day": "A forradalom napja",
  "Russia Day": "Oroszország napja",
  "Saint Brigid's Day": "Szent Brigitta napja",
  "Saint Clement of Ohrid Day": "Ohridi Szent Kelemen napja",
  "Saint Devota's Day": "Szent Devota napja",
  "Saint George": "Szent György napja",
  "Saint George's Day": "Szent György napja",
  "Saint John the Baptist": "Keresztelő Szent János napja",
  "Saint Joseph the Worker": "Munkás Szent József",
  "Saint Joseph's Day": "Szent József napja",
  "Saint Patrick's Day": "Szent Patrik napja",
  "Saint Peter and Saint Paul": "Szent Péter és Szent Pál",
  "Saints Cyril and Methodius Day": CYRIL,
  "Second day of Christmas": "Karácsony másnapja",
  "Sette Giugno": "Június 7. (Sette Giugno)",
  "Slovak National Uprising anniversary": "A szlovák nemzeti felkelés évfordulója",
  "Solemnity of Mary, Mother of God": "Szűz Mária, Isten Anyja főünnepe",
  "South Capital's Day Cahul": "Cahul, a déli főváros napja",
  "Sovereign's birthday": "Az uralkodó születésnapja",
  "Spring Bank Holiday": "Tavaszi munkaszüneti nap",
  "Spring Day": "A tavasz napja",
  "St. Andrew's Day": "Szent András napja",
  "St. Cyril and Methodius Day": CYRIL,
  "St. Francis of Assisi's Day": "Assisi Szent Ferenc napja",
  "St. John's Day": "Szent János napja",
  "St. Stephen's Day": "Szent István vértanú napja (karácsony másnapja)",
  "St. Wenceslas Day": "Szent Vencel napja",
  "State Foundation Day": "Az államalapítás ünnepe",
  "Statehood Day": "Az államiság napja",
  "Struggle for Freedom and Democracy Day": "A szabadságért és a demokráciáért folytatott küzdelem napja",
  "Summer Day": "A nyár napja",
  "Swiss National Day": "Svájc nemzeti ünnepe",
  "The Day of Restoration of the State of Lithuania": "A litván állam helyreállításának napja",
  "The Feast of San Marino and the Republic": "San Marino és a köztársaság ünnepe",
  "The Immaculate Conception": IMMACULATE,
  "Unification Day": "Az egyesülés napja",
  "Union Day/Small Union": "Az egyesülés napja (kis egyesülés)",
  "Unity Day": "Az egység napja",
  "Victory Day": "A győzelem napja",
  "Victory and Commemoration Day": "A győzelem és az emlékezés napja",
  "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders": "A győzelem és a haza hálaadásának napja, a horvát védők napja",
  "Victory day over Nazism in World War II": "A nácizmus feletti győzelem napja a második világháborúban",
  "Victory in Europe Day": "Az európai győzelem napja",
  "Whit Monday": "Pünkösdhétfő",
  "Worker's Day": WORKERS,
  "Youth Day": "Az ifjúság napja",
};
